url: https://antonbeliakovucsd.github.io
baseurl: /Capstone/

# Site settings
title: Heritability & Causal Variance in Cancer Genomics
email: 
description: "Exploring the relationship between heritability estimates and the causal variance exhibited by SNPs for a range of diseases"


# Team names, titles and social links
mentor:
- name: Dr. Amariuta
  pic: 1
  position: Mentor
  email: tamariutabartell@ucsd.edu
  social:
    - title: linkedin
      url:

people:
- name: Gurman Dhaliwal
  pic: 2
  position: Researcher
  email: gdhaliwa@ucsd.edu 
  social:
    - title: github
      url: https://github.com/GKD-stack
    - title: linkedin
      url:

- name: Lihao Liu
  pic: 3
  position: Researcher
  email: liliu@ucsd.edu
  social:
    - title: github
      url: https://github.com/llh1201
    - title: linkedin
      url:

- name: Anton Beliakov
  pic: 4
  position: Researcher
  email: abeliako@ucsd.edu
  social:
    - title: github
      url: https://github.com/AntonBeliakovUCSD
    - title: linkedin
      url: www.linkedin.com/in/anton-beliakov-a3b112217



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/AntonBeliakovUCSD/Capstone
  - title: report
    url: https://drive.google.com/file/d/1dDTIaAgFiv3PqccQx0vxUpQeoQchqfxl/view?usp=sharing

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
