url: https://antonbeliakovucsd.github.io
baseurl: /Capstone/

# Site settings
title: Heritability & Causal Variance in Cancer Genomics
email: 
description: "Exploring the relationship between heritability estimates and the causal variance exhibited by SNPs for a range of diseases like cancer"


# Team names, titles and social links

people:
- name: Gurman Dhaliwal
  pic: Gurman
  position: Researcher
  email: gdhaliwa@ucsd.edu 
  social:
    - title: github
      url: https://github.com/GKD-stack
    - title: linkedin
      url: https://www.linkedin.com/in/gurman-dhaliwal/

- name: Lihao Liu
  pic: Lihao
  position: Researcher
  email: liliu@ucsd.edu
  social:
    - title: github
      url: https://github.com/llh1201
    - title: linkedin
      url: https://www.linkedin.com/in/lihaoliu1201/

- name: Anton Beliakov
  pic: Anton
  position: Researcher
  email: abeliako@ucsd.edu
  social:
    - title: github
      url: https://github.com/AntonBeliakovUCSD
    - title: linkedin
      url: https://www.linkedin.com/in/anton-k-beliakov

- name: Dr. Amariuta
  pic: Amariuta
  position: Mentor
  email: tamariutabartell@ucsd.edu
  social:
    - title: website
      url: https://www.amariutalab.org/



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/AntonBeliakovUCSD/Capstone
  - title: report
    url: https://drive.google.com/file/d/1dDTIaAgFiv3PqccQx0vxUpQeoQchqfxl/view?usp=sharing

# Build settings
markdown: kramdown
permalink: pretty
