url: https://antonbeliakovucsd.github.io
baseurl: /Capstone/

# Site settings
title: How does Heritability Correlate With Causal Variance?
email: 
description: "Exploring the relationship between heritability estimates and the causal variance exhibited by SNPs for a range of diseases"


# Team names, titles and social links
people:
- name: Gurman Dhaliwal
  pic: 1
  position: Researcher
  social:
    - title: Email
      url: # gdhaliwa@ucsd.edu
    - title: 
      url: #
    - title: 
      url: #

- name: Lihao Liu
  pic: 2
  position: Researcher
  social:
    - title: Email
      url: # liliu@ucsd.edu
    - title: 
      url: #
    - title: 
      url: #

- name: Anton Beliakov
  pic: 3
  position: Researcher
  social:
    - title: Email
      url: # abeliako@ucsd.edu
    - title:
      url: #
    - title:
      url: #

- name: Dr. Amariuta
  pic: 4
  position: Mentor
  social:
    - title: Email
      url: # tamariutabartell@ucsd.edu
    - title:
      url: #
    - title:
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
